CREATE TABLE IF NOT EXISTS categories_small (
  id INT AUTO_INCREMENT PRIMARY KEY,
  category_middle_id INT NOT NULL,
  name VARCHAR(100) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (category_middle_id) REFERENCES categories_middle(id)
);