SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS product_orders;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS categories_small;
DROP TABLE IF EXISTS categories_middle;
DROP TABLE IF EXISTS categories_large;
DROP TABLE IF EXISTS manufacturers;
DROP TABLE IF EXISTS admins;
DROP TABLE IF EXISTS stores;
DROP TABLE IF EXISTS positions;
DROP TABLE IF EXISTS roles;

SET FOREIGN_KEY_CHECKS = 1;